pipeline:
  deploy:
    image: plugins/docker
    dockerfile: Dockerfile
    auto_tag: true
    auto_tag_suffix: happy
    repo: kyos0109/php-fpm-opcache
    secrets: [ docker_username, docker_password ]
    when:
      branch:
        exclude: develop
        include: [ master, release/*, hostfix/*, refs/tags/* ]
      events: [ tag, push, pull_request ]
  notify:
    image: kyos0109/drone-line-notify:latest
    secrets: [ token_secret ]
    message: |
        Status: {{.BuildStatus}}
        Repo: {{.RepoName }}
        Branch: {{.RepoBranch}}
        Build Num: {{.BuildNum}}
        Commit ID: {{.CommitID}}
        Author: {{.Author}}
        Commit Msg: {{.CommitMsg}}
    when:
      branch:
        exclude: develop
        include: [ master, release/*, hostfix/*, refs/tags/* ]
      events: [ tag, push, pull_request ]
